language: cpp
env:
  global:
  - FORCE_INSTALL=1

matrix:
  include:
  - os: osx
    name: "Check Shell Scripts"

    script:
    - HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install shellcheck
    - find . \( -name "*.tool" -o -name "*.command" -o -name "*.sh" \) -exec shellcheck --severity=info {} \;

  - os: osx
    name: "Build macOS XCODE5"
    osx_image: xcode10.2
    compiler: clang

    script:
    - "./macbuild.tool"


  - os: linux
    name: "Build Linux CLANGPDB/GCC5"
    dist: xenial
    addons:
      apt:
        packages:
        - nasm
        - uuid-dev

    script:
    - export PYTHON_COMMAND=python3 # Something is broken in Travis CI environment, it asks for python3.7.
    - llvmfile="clang+llvm-9.0.1-x86_64-linux-gnu-ubuntu-16.04"
    - curl -LO "https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/${llvmfile}.tar.xz" || exit 1
    - llvmsum=$(shasum -a 256 "${llvmfile}.tar.xz" | cut -f1 -d' ')
    - llvmexpsum="1af280e96fec62acf5f3bb525e36baafe09f95f940dc9806e22809a83dfff4f8"
    - if [ "$llvmsum" != "$llvmexpsum" ]; then echo "Invalid LLVM checksum $llvmsum" ; exit 1 ; fi
    - tar -xf "${llvmfile}.tar.xz" || exit 1
    - export PATH="$(pwd)/${llvmfile}/bin:$PATH"
    - "./macbuild.tool"

  - os: linux
    name: "Build Linux CLANG38"
    dist: xenial
    addons:
      apt:
        packages:
        - nasm
        - uuid-dev
        - clang-8
        - llvm-8-dev

    script:
    - export PYTHON_COMMAND=python3 # Something is broken in Travis CI environment, it asks for python3.7.
    - sudo apt-get remove llvm-3.8 libllvm3.8 # Move LLVM 3.8 out of the way.
    - export PATH="/usr/lib/llvm-8/bin:$PATH" # Default compiler (7.0 or 3.8) has no LTO plugin.
    - export TOOLCHAINS=CLANG38
    - "./macbuild.tool"
